package engine

/* Test autogenerated with the tool go-test-gen. Created 2024-06-26 16:52:18 Wednesday */

import (
	"os"
	"testing"

	"github.com/dterbah/gopm/core"
	"github.com/stretchr/testify/assert"
)

const PROJECT_NAME = "dummy"
const ENTRY_POINT = "main.go"
const LICENSE_NAME = "MIT"
const GIT = "github.com/test"

func cleanup() {
	os.RemoveAll(PROJECT_NAME)
}

func TestInitProject(t *testing.T) {
	defer cleanup()
	assert := assert.New(t)

	config := core.NewGoPMConfig()

	// without project name
	err := InitProject(*config)
	assert.NotNil(err)

	// without entry point
	config.ProjectName = PROJECT_NAME
	err = InitProject(*config)
	assert.NotNil(err)

	// without license
	config.EntryPoint = ENTRY_POINT
	err = InitProject(*config)
	assert.NotNil(err)

	// without repository name
	config.License = LICENSE_NAME
	err = InitProject(*config)
	assert.NotNil(err)

	config.Git = GIT
	err = InitProject(*config)
	assert.Nil(err)
}

func TestInstallDependencies(t *testing.T) {
	defer cleanup()
	assert := assert.New(t)
	dependencies := []string{"github.com/dterbah/gods", "github.com/sirupsen/logrus@v1.9.3"}
	config := core.NewGoPMConfig()
	config.ProjectName = PROJECT_NAME
	config.EntryPoint = ENTRY_POINT
	config.License = LICENSE_NAME
	config.Git = GIT

	// test without file config
	err := InstallDependencies(dependencies)
	assert.NotNil(err)

	InitProject(*config)
	os.Chdir(config.ProjectName)

	// test with invalid dependencies
	err = InstallDependencies([]string{"dummy-dependency"})
	assert.NotNil(err)

	// test with valid dependencies
	err = InstallDependencies(dependencies)
	assert.Nil(err)

	// test without dependencies

	os.Chdir("..")
}

func TestRunScript(t *testing.T) {
	// todo implement
}
